### ISSUE TITLE
Empty static.go

### ISSUE THREAD

**Issue by Sh3lldor** [skx/implant#18]
I have something like this:
data
    assets
        somecode.exe

and after running:  implant.exe -input .\data\

The tools works great with little files but with exe files  I get empty static.go file.
 any ideas ?

**Comment by skx** [comment]
I think you're saying you have an input-structure like so:

      data/
      data/assets/
      data/assets/somecode.exe

I'll have to check over the error-handling, but so far I've never seen an empty file.

You say "works great with little files".  Could you give me an idea of the filesize which is failing, and I'll try to reproduce here.

**Comment by Sh3lldor** [comment]
[msgbox.txt](https://github.com/skx/implant/files/5267500/msgbox.txt)

file Attached (its c code that does msgbox encoded in base64)

**Comment by skx** [comment]
I can't reproduce this here

* I made an empty directory
* I downloaded your executable into it.
* I ran implant, and the generated `static.go` had the file as expected:

```
mkdir tmp/
mkdir tmp/sub/
wget -O tmp/sub/test.exe https://github.com/skx/implant/files/5267500/msgbox.txt
implant -input tmp/
```

The generated file is present, as expected:

```
 $ grep tmp static.go
	"tmp/sub/test.exe": {
		Filename: "tmp/sub/test.exe",
```

Is there anything else you can think of that might be different?  (I wonder if you're running Windows - since your input path has `.\` in it ..)

**Comment by Sh3lldor** [comment]
This one is on windows, maybe its the problem ? but It worked with small text file.
let me try on my linux machine.

**Comment by Sh3lldor** [comment]
Works Great in linux !, I guess some parsing error at windows :( 
Thnak you for all the help, i will just compile my go in linux for windows.
Have a good one !
